# Generated by Django 3.2.6 on 2021-08-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('date_published', models.DateField()),
                ('isbn', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('number_of_pages', models.IntegerField(blank=True, null=True)),
                ('link_to_cover', models.TextField()),
                ('language_of_publication', models.CharField(max_length=200)),
            ],
        ),
    ]
